**********************************************************************************************
**********************************************************************************************
** Dofile: Eventus ID recoding DEMO
** Author: Javier Osorio
**
** Project: Eventus ID 2.0
** Date: October, 2014
**
**********************************************************************************************
**********************************************************************************************

****************************************************************************
****************************************************************************
**************
**************
************** MASTER DOFILE 
**************
**************
****************************************************************************
****************************************************************************


clear

set more off

****************************************************************************
****************************************************************************
* Set working directory
cd "C:\Users\Javier\Documents\My Dropbox\Eventus ID paper\SSCR Publication\SSCR_replication\Eventus_ID_2.0_DEMO\Recoding_dofiles"


****************************************************************************
* Load the data
	/* Copy the "codigos_Events_DEMO.txt" generated by Eventus and paste it in the "Recoding_dofiles" folder.
	   Make sure you use the Eventus ID output containing only numeric codes. 
	   Change the name of your file according to your machine generated data. */
	
	 insheet using "codigos_Events_DEMO.txt"  /* corpus*/

	 
****************************************************************************
* Recoding events 
set more off
do "1_recoding_fv"


****************************************************************************
* Recoding special cases
* This is a post-script was added as part of the validation and recoding process 
set more off
do "2_recoding_special_cases"


****************************************************************************
* Recoding events 
set more off
do "3_disaggregate_location_fv"


****************************************************************************
* Fill in locations
set more off
do "4_fill_in_locations_fv"


****************************************************************************
* Fill in locations
set more off
do "5_aggregate_events_fv2"


****************************************************************************
* Label variables
set more off
do "6_label_variables_fv2"


****************************************************************************
* Generate graphs
* This section replicates Figures 2 and 3 in the document "Eventus_ID_extended_application"
set more off
do "7_graphs_v1"


****************************************************************************
* Regression analysis
* This section replicates Tables 5 and 6 in the document "Eventus_ID_extended_application"
set more off
do "8_analysis"


****************************************************************************
****************************************************************************
**************
**************
************** END OF MASTER DOFILE 
**************
**************
****************************************************************************
****************************************************************************






